name: aliyundrive

on:
  workflow_dispatch:
  schedule:
    - cron: "23 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '12.x', '14.x', '16.x', '18.x' ]

    steps:
      - name: Delete node_modules
        run: rm -rf node_modules

      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependency packages
        run: |
          npm cache clean --force
          npm install

      - name: Run
        run: |
          node sudojia_aliyundrive.js
        env:
          ALI_REFRESH_TOKEN: ${{ secrets.ALI_REFRESH_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1