name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "23 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Delete
        run: |
          rm -rf node_modules
          rm package.json
          rm package-lock.json